apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

resources:
  - base/namespace.yaml
  - base/ingress.yaml
  - services/auth-service/deployment.yaml
  - services/auth-service/service.yaml
  - services/business-service/deployment.yaml
  - services/business-service/service.yaml
  - services/project-service/deployment.yaml
  - services/project-service/service.yaml